function bacthqsmprocessingproc(getbrowsedirectory)

h.figure = figure('position' , [500 440 400 500]);
set(h.figure, 'Color', [0.43 0.76 0.70]);

h.browsedirectory = uicontrol(h.figure ,'Style','text',...
    'String','Working Directory',...
    'Position',[20 450 130 20]);

h.browsedirectoryvalue = uicontrol(h.figure ,'Style','edit',...
    'String','test',...
    'Position',[160 450 200 20]);

set(h.browsedirectoryvalue,'String', getbrowsedirectory);

h.b0 = uicontrol(h.figure ,'Style','text',...
    'String','B0',...
    'Position',[20 410 130 20]);

h.b0value = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[160 410 200 20]);

h.analysis = uicontrol(h.figure ,'Style','text',...
    'String','Analysis',...
    'Position',[20 370 130 20]);

h.readdicom = uicontrol(h.figure ,'Style','checkbox',...
    'String','    Read DICOM',...
    'Position',[160 370 200 20],'HandleVisibility','off');

h.phaseunwrapping = uicontrol(h.figure ,'Style','checkbox',...
    'String','    Phase Unwrapping',...
    'Position',[160 340 200 20],'HandleVisibility','off');

h.vsharp = uicontrol(h.figure ,'Style','checkbox',...
    'String','    V-SHARP',...
    'Position',[160 310 200 20],'HandleVisibility','off');

h.starqsm = uicontrol(h.figure ,'Style','checkbox',...
    'String','    Star QSM',...
    'Position',[160 280 200 20],'HandleVisibility','off');

h.ilsqrqsm = uicontrol(h.figure ,'Style','checkbox',...
    'String','    iLSQR QSM',...
    'Position',[160 250 200 20],'HandleVisibility','off');

h.gobutton = uicontrol(h.figure ,'Style','pushbutton',...
    'String','Start',...
    'Position',[148 100 80 20]);

set(h.gobutton, 'callback',{@gobuttonqsmsingleproc, h});


end