function filestructgenerate13(dir_value)

h.figure = figure('position' , [600 440 400 200]);
set(h.figure, 'Color', [0.43 0.76 0.70]);

h.subjectcodeprompt = uicontrol(h.figure ,'Style','text',...
    'String','Subject Code',...
    'Position',[20 120 150 20]);

h.subjectcodeaddition = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[200 120 150 20]);

h.numberofsubjects = uicontrol(h.figure ,'Style','text',...
    'String','Upload Data',...
    'Position',[20 80 150 20]);

h.meg_data = uicontrol(h.figure ,'Style','pushbutton',...
    'String','MEG',...
    'Position',[200 80 60 20]);

set(h.meg_data,'callback', {@megbrowseproc,h});

h.meg_mri= uicontrol(h.figure ,'Style','pushbutton',...
    'String','MRI',...
    'Position',[270 80 80 20]);

h.addsubjectcode = uicontrol(h.figure ,'Style','pushbutton',...
    'String','Add',...
    'Position',[200 30 150 20]);

set(h.meg_mri,'callback', {@single_meg_dataproc,h});
set(h.addsubjectcode,'callback', {@addsubjectmegsingle,h});


end