function filestructgenerate(dir_value)

    
    h.figure = figure('position' , [600 440 400 200]);
    set(h.figure, 'Color', [0.43 0.76 0.70]);
    
    h.numberofsubjects = uicontrol(h.figure ,'Style','text',...
                                             'String','Number of Subjects',...
                                             'Position',[20 160 150 20]);
                                         
    h.numberofsubjectsvalue = uicontrol(h.figure ,'Style','edit',...
                                                  'String','',...
                                                  'Position',[200 160 150 20]);
                                              
    h.subjectcodeprompt = uicontrol(h.figure ,'Style','text',...
                                             'String','Subject Code',...
                                             'Position',[20 120 150 20]);
                                         
    h.subjectcodeaddition = uicontrol(h.figure ,'Style','edit',...
                                                'String','',...
                                                'Position',[200 120 80 20]);
   
    h.addsubjectcode = uicontrol(h.figure ,'Style','pushbutton',...
                                           'String','Add',...
                                           'Position',[290 120 60 20]);
                                       
  
    h.addsubjectcode = uicontrol(h.figure ,'Style','pushbutton',...
                                           'String','MRS',...
                                           'Position',[290 120 60 20]);
                                       
    h.addsubjectcode = uicontrol(h.figure ,'Style','pushbutton',...
                                           'String','MRI',...
                                           'Position',[290 120 60 20]);
                                       
end