function filestructgenerate11(dir_value)


h.figure = figure('position' , [600 440 400 200]);
set(h.figure, 'Color', [0.43 0.76 0.70]);

h.numberofsubjects = uicontrol(h.figure ,'Style','text',...
    'String','Label (MRS Mask)',...
    'Position',[20 160 150 20]);

h.labelMRSvalue = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[200 160 150 20]);

h.subjectcodeprompt = uicontrol(h.figure ,'Style','text',...
    'String','Subject Code',...
    'Position',[20 120 150 20]);

h.subjectcodeaddition = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[200 120 150 20]);

h.numberofsubjects = uicontrol(h.figure ,'Style','text',...
    'String','Upload Data',...
    'Position',[20 80 150 20]);

h.mrs_data = uicontrol(h.figure ,'Style','pushbutton',...
    'String','MRS',...
    'Position',[200 80 60 20]);

set(h.mrs_data,'callback', {@mrs_dataproc,h});

h.mri_mrs_data = uicontrol(h.figure ,'Style','pushbutton',...
    'String','MRI (MRS)',...
    'Position',[270 80 80 20]);

h.addsubjectcode = uicontrol(h.figure ,'Style','pushbutton',...
    'String','Add',...
    'Position',[200 30 150 20]);

set(h.mri_mrs_data,'callback', {@mri_mrs_dataproc,h});
set(h.addsubjectcode,'callback', {@addsubjectcodeprocMRSonly,h});

end