function singleqsmfmriproc(getbrowsedirectory)

h.figure = figure('position' , [500 440 400 500],'name','PRATEEK', 'NumberTitle','off');
set(h.figure, 'Color', [0.43 0.76 0.70]);

h.browsedirectory = uicontrol(h.figure ,'Style','text',...
    'String','Working Directory',...
    'Position',[20 450 130 20]);

h.browsedirectoryvalue = uicontrol(h.figure ,'Style','edit',...
    'String','test',...
    'Position',[160 450 200 20]);

set(h.browsedirectoryvalue,'String', getbrowsedirectory);

h.b0 = uicontrol(h.figure ,'Style','text',...
    'String','B0',...
    'Position',[20 410 130 20]);

h.b0value = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[160 410 200 20]);

h.numchar = uicontrol(h.figure ,'Style','text',...
    'String','ID Length',...
    'Position',[20 370 130 20]);

h.numcharvaluevalue = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[160 370 200 20]);

h.folderprefix= uicontrol(h.figure ,'Style','text',...
    'String','Folder Prefix',...
    'Position',[20 330 130 20]);

h.folderprefixvalue = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[160 330 200 20]);

h.echoprefix= uicontrol(h.figure ,'Style','text',...
    'String','Echo Prefix',...
    'Position',[20 290 130 20]);

h.echoprefixvalue = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[160 290 200 20]);

h.analysis = uicontrol(h.figure ,'Style','text',...
    'String','Analysis',...
    'Position',[20 250 130 20]);

h.readdicom = uicontrol(h.figure ,'Style','checkbox',...
    'String','    Read DICOM',...
    'Position',[160 250 200 20],'HandleVisibility','off');

h.phaseunwrapping = uicontrol(h.figure ,'Style','checkbox',...
    'String','    Phase Unwrapping',...
    'Position',[160 220 200 20],'HandleVisibility','off');

h.vsharp = uicontrol(h.figure ,'Style','checkbox',...
    'String','    V-SHARP',...
    'Position',[160 190 200 20],'HandleVisibility','off');

% h.starqsm = uicontrol(h.figure ,'Style','checkbox',...
%     'String','    Star QSM',...
%     'Position',[160 280 200 20],'HandleVisibility','off');

h.ilsqrqsm = uicontrol(h.figure ,'Style','checkbox',...
    'String','    iLSQR QSM',...
    'Position',[160 160 200 20],'HandleVisibility','off');

h.tr = uicontrol(h.figure ,'Style','text',...
    'String','TR(s)',...
    'Position',[20 120 130 20]);

h.trvalue = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[160 120 200 20]);

h.slice = uicontrol(h.figure ,'Style','text',...
    'String','Slice Number',...
    'Position',[20 90 130 20]);

h.slicenumber = uicontrol(h.figure ,'Style','edit',...
    'String','',...
    'Position',[160 90 200 20]);

h.proc = uicontrol(h.figure ,'Style','text',...
    'String','Analysis',...
    'Position',[20 60 130 20]);

h.procpreprocessing = uicontrol(h.figure ,'Style','checkbox',...
    'String','    Preprocessing',...
    'Position',[160 60 200 20],'HandleVisibility','off');

h.subjectlevelanalysis = uicontrol(h.figure ,'Style','checkbox',...
    'String','    Subject Level Analysis',...
    'Position',[160 30 200 20],'HandleVisibility','off');

h.gobutton = uicontrol(h.figure ,'Style','pushbutton',...
    'String','Start',...
    'Position',[148 2 80 20]);

set(h.gobutton, 'callback',{@gobuttonfmriqsmproc, h});

end